theme: jekyll-theme-minimal
title: LLM Prompts Library Blog
description: Professional AI prompts for developers and content creators
author: Ayman Aboghonim
github:
  repository_url: https://github.com/aymanaboghonim/llm-prompts
  repository_name: llm-prompts

plugins:
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - CHANGELOG.md
